openapi: 3.0.0
info:
  version: 1.0.0
  title: GeoJSON format
  description: >
    This document defines the GeoJSON format as an OpenAPI.
    It contains the definitions for 'Feature' object and 'FeatureCollection'
    objects, as well as the definitions for all 'Geometry' objects.
    It conforms with the 'RFC-7946' standard from IETF (August 2016 version)
    
    Kudos to @bubbobne and @idkw whose code helped me not start from scratch
    https://gist.github.com/bubbobne/fe5f2db65acf039be6a9fd92fc9c7233
  termsOfService: 'no'
  contact:
    name: Zitoun
    email: 'zitoun@gmail.com'
  license:
    name: GPLv3
    url: 'https://www.gnu.org/licenses/gpl-3.0.html'

#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
externalDocs:
  description: Official GeoJSON specification – 'IETF RFC-7946' (August 2016)
  url: 'https://tools.ietf.org/html/rfc7946'

#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
security:
  - UserSecurity: []

#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
servers:
  - url: 'http://myHost/'

#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
paths:
  #=============================================================================
  '/geometry':
    get:
      summary: Get an array of GeoJSON Geometry objects
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GeometryCollection'
        '400':
          $ref: '#/components/responses/BadRequest400ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized401ErrorResponse'
        '500':
          $ref: '#/components/responses/Server500ErrorResponse'
    post:
      summary: Create new GeoJSON Geometry object
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Geometry'
        required: true
      responses:
        '201':
          description: New GeoJSON Geometry object created
        '400':
          $ref: '#/components/responses/BadRequest400ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized401ErrorResponse'
        '403':
          $ref: '#/components/responses/Forbidden403ErrorResponse'
        '500':
          $ref: '#/components/responses/Server500ErrorResponse'

#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
components:

  #=============================================================================
  responses:
    'BadRequest400ErrorResponse':
      description: The JSON is not valid
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/BasicError'
              - type: object
                properties:
                  'type':
                    type: integer
                    enum: [400]

    'Unauthorized401ErrorResponse':
      description: The request requires the user an authentification
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/BasicError'
              - type: object
                properties:
                  'type':
                    type: integer
                    enum: [401]

    'Forbidden403ErrorResponse':
      description: The access is not allowed
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/BasicError'
              - type: object
                properties:
                  'type':
                    type: integer
                    enum: [403]

    'NotFound404ErrorResponse':
      description: The resource was not found
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/BasicError'
              - type: object
                properties:
                  'type':
                    type: integer
                    enum: [403]

    'Server500ErrorResponse':
      description: An unexpected error occured.
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/BasicError'
              - type: object
                properties:
                  'type':
                    type: integer
                    enum: [500]
  #=============================================================================
  securitySchemes:
    'UserSecurity':
      type: http
      scheme: basic

  #=============================================================================
  schemas:

    #---------------------------------------------------------------------------
    'BasicError':
      required:
        - code
        - message
      properties:
        'code':
          type: integer
          minimum: 100
          maximum: 600
        'message':
          type: string

    #---------------------------------------------------------------------------
    'GeoJsonObject':
      $ref: schemas/GeoJsonObject.yaml

    'Geometry':
      $ref: schemas/Geometry.yaml

    'GeometryElement':
      $ref: schemas/GeometryElement.yaml
      
    'Feature':
      $ref: schemas/Feature.yaml
      
    'FeatureCollection':
      $ref: schemas/FeatureCollection.yaml

    'Position':
      $ref: schemas/Position.yaml

    'LineStringCoordinates':
      $ref: schemas/LineStringCoordinates.yaml

    'LinearRing':
      $ref: schemas/LinearRing.yaml

    'Point':
      $ref: schemas/Point.yaml

    'MultiPoint':
      $ref: schemas/MultiPoint.yaml

    'LineString':
      $ref: schemas/LineString.yaml

    'MultiLineString':
      $ref: schemas/MultiLineString.yaml

    'Polygon':
      $ref: schemas/Polygon.yaml

    'MultiPolygon':
      $ref: schemas/MultiPolygon.yaml

    'GeometryCollection':
      $ref: schemas/GeometryCollection.yaml

#•••••••••••••••••••••••••••••••••••[ EOF ]••••••••••••••••••••••••••••••••••••#
